base: 'https://typo312-videotraining.ddev.site/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=26'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_AT.utf8
    navigationTitle: DE
    flag: at
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
